const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..','..','..');
const claims=JSON.parse(fs.readFileSync(path.join(root,'data','research','claim-inventory.json'),'utf8'));
const sources=JSON.parse(fs.readFileSync(path.join(root,'data','research','source-inventory.json'),'utf8'));
const canonical=JSON.parse(fs.readFileSync(path.join(root,'data','research','canonical-source-set.json'),'utf8'));
const auditedPath=path.join(root,'data','research','source-url-audit.json');
const audited=fs.existsSync(auditedPath)?JSON.parse(fs.readFileSync(auditedPath,'utf8')):[];
const sourceIds=new Set(sources.map(x=>x.sourceId));
assert.equal(sourceIds.size,sources.length,'duplicate source IDs');
assert.equal(claims.every(x=>x.currentSourceIds.every(id=>sourceIds.has(id))),true,'invalid source ID');
assert.equal(sources.filter(x=>x.sourceStatus==='SEARCH_INDEX_ONLY').every(x=>x.sourceAccessible===false),true,'search-index source must be inaccessible');
assert.equal(claims.filter(x=>x.currentConfidence==='VERIFIED_CURRENT').every(x=>x.currentSourceIds.length>0),true,'verified claim requires source');
assert.equal(claims.filter(x=>x.currentConfidence==='HIGH').every(x=>x.currentSourceIds.some(id=>sources.find(s=>s.sourceId===id)?.sourceStatus!=='SEARCH_INDEX_ONLY')),true,'search index cannot be HIGH');
assert.equal(new Set(canonical.map(x=>x.canonicalUrl)).size,canonical.length,'duplicate canonical source in canonical set');
assert.equal(canonical.reduce((sum,x)=>sum+x.sourceIds.length,0),sources.length,'same source counted twice or omitted');
assert.equal(audited.filter(x=>x.sourceStatus==='DEAD_LINK').some(x=>/CURRENT/.test(x.freshness||'')),false,'dead source still marked CURRENT');
assert.equal(claims.filter(x=>x.currentConfidence==='VERIFIED_CURRENT').some(x=>x.currentSourceIds.some(id=>sources.find(s=>s.sourceId===id)?.sourceStatus==='SEARCH_INDEX_ONLY')),false,'search index used as official fact');
const specials=fs.readFileSync(path.join(root,'旅遊指南','assets','special-items-data.js'),'utf8');
assert.equal(/2025[^\n]{0,120}AVAILABLE_DURING_TRIP/.test(specials),false,'2025 seasonal event shown as 2026 confirmed');
assert.equal(/Perplexity[^\n]{0,120}(verified|確認)/i.test(JSON.stringify(claims)),false,'Perplexity answer used without original URL');
console.log(`PASS source inventory: ${claims.length} claims, ${sources.length} sources, ${canonical.length} canonical sources, valid references`);
