const fs=require('node:fs');const path=require('node:path');const s=require('./lib/social.cjs');
const root=path.resolve(__dirname,'..','..'),raw=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures','records.json'),'utf8')),records=s.dedupe(raw.map(s.normalizeRecord));
fs.mkdirSync(path.join(root,'data','social'),{recursive:true});fs.writeFileSync(path.join(root,'data','social','research-candidates.json'),JSON.stringify(records,null,2)+'\n');
const registry=JSON.parse(fs.readFileSync(path.join(__dirname,'registry','query-families.json'),'utf8'));
const statePath=path.join(root,'data','social','query-state.json');
const state=fs.existsSync(statePath)?JSON.parse(fs.readFileSync(statePath,'utf8')):{};
const entities=[{id:'ueno-toshogu',name:'上野東照宮'},{id:'enoshima',name:'江之島'},{id:'shibuya-parco',name:'SHIBUYA PARCO'},{id:'shinagawa-aquarium',name:'品川水族館'},{id:'yokohama-redbrick',name:'橫濱紅磚倉庫'},{id:'confirmed-restaurants',name:'東京 行程餐廳'}];
const rotation=s.rotateQueries(registry,state,entities);
fs.writeFileSync(statePath,JSON.stringify({...rotation.nextState,updatedAt:new Date().toISOString()},null,2)+'\n');
const report={runAt:new Date().toISOString(),sourcesRefreshed:records.length,platformDistribution:Object.fromEntries([...new Set(records.map(x=>x.platform))].map(platform=>[platform,records.filter(x=>x.platform===platform).length])),confidenceDistribution:Object.fromEntries(['HIGH','MEDIUM','LOW','SEARCH_INDEX_ONLY'].map(level=>[level,records.filter(x=>x.confidence===level).length])),officialVerificationCount:records.filter(x=>x.officialVerification==='CONFIRMED').length,publishable:records.filter(s.publishable).length,queryRotation:{family:rotation.familyId,queries:rotation.queries},perplexity:{status:s.perplexityStatus(process.env),failureMode:'FAIL_SOFT',triggers:registry.perplexityTriggers}};fs.writeFileSync(path.join(root,'data','reports','latest-social-refresh.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
